config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/users/guest_sign_in', to: 'users#guest_sign_in'
  get 'user_infos/bmi'
  root to: 'user_infos#index'
  resources :user_infos, only: [:index,:new,:create,:destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_infos
  #validates :nickname, presence: true, length: { maximum: 6 }
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user
  validates :height, presence: true
  validates :weight, presence: true
  validates :BMI, presence: true
  def self.bmi(weight,height)
    return weight / (height/100.to_f)**2
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  before_action :move_to_index, except: :index
  
def index
  @user_infos = UserInfo.all
end

def bmi
  @user_infos = UserInfo.all
end


def new
  @user_info = UserInfo.new
end

def destroy
  @user_info = UserInfo.find(params[:id])
  @user_info.destroy
  redirect_to root_path
end


def create
  weight = params[:user_info][:weight].to_i
  height = params[:user_info][:height].to_i
  bmi = UserInfo.bmi(weight,height)
  UserInfo.create(user_info_params(bmi))
  redirect_to root_path
end




def edit
  @user_info = UserInfo.find(params[:id])
end

private
  def user_info_params(bmi)
    params.require(:user_info).permit(:weight, :height, :BMI).merge(user_id: current_user.id,BMI: bmi)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user_info = UserInfo.find(params[:id]) 
  end

  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = 'guest' 
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Health</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
  </head>

  <body>
  <header>
  <div class='top-page-header'>
</div>
  </div>
  <div class='nav'>
  
    <ul class='lists-left'>
      <li> <%= link_to 'Health', root_path, class: "health-class" %></li>
      <li><%= link_to '体重登録', new_user_info_path, class: "weight" %></li>
      <li><%= link_to 'BMI', user_infos_bmi_path, class: "BMI" %></li>
    </ul>
    <ul class='lists-right'>
    <li><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: 'guest' %></li>
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, "ゲスト", class: "user-nickname"%></li>
      <li><%= link_to 'ログアウト',destroy_user_session_path , method: :delete, class: "logout"  %> </li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
       <% end %>
    </ul>
  </div>
</header>
<div class="contents">
      <div class="first-view"> 
      </div>
      
    <%= yield %>
    <footer>
      <p>
        Copyright©︎ TAKUYA MIYAMA.  ALL Rights Reserved.
      </p>
    </footer>
  </body>
</html>

app/views/user_infos/bmi.html.erb
<div class="contents row">
<% @user_infos.each do |user_info| %>
<div class="user_info"> 
<%= link_to '削除する', user_info_path(user_info.id), method: :delete %>
 <div class="weight">
      日付：<%= user_info.created_at.strftime("%m月%d日") %>
    </div>
    <div class="BMI">
      BMI：<%= user_info.BMI %>
    </div>
  </div>
<% end %>
</div>


<html lang="ja">

<head>
  <meta charset="utf-8">
　<title>グラフ</title> 
</head>
<body>
  <canvas id="myLineChart"></canvas>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>

  <script>
  var ctx = document.getElementById("myLineChart");
  var myLineChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: [<% @user_infos.each_with_index do |user_info| %> "<%= user_info.created_at.strftime("%m月%d日") %>" ,<% end %>],
      datasets: [
        
     
        {
          label: 'BMI',
          data: [ <% @user_infos.each_with_index do |user_info| %><%= user_info.BMI %> ,<% end %> ],
          borderColor: "rgba(0,0,255,1)",
          backgroundColor: "rgba(0,0,0,0)"
        },  

      ],
    },
    options: {
      title: {
        display: true,
        
      },
      scales: {
        yAxes: [{
          ticks: {
            suggestedMax: 40,
            suggestedMin: 0,
            stepSize: 10,
            callback: function(value, index, values){
              return  value +  ''
            }
          }
        }]
      },
    }
  });
  </script>
</body>

</html>

app/views/user_infos/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @user_info, local: true) do |form| %>
      <%= form.text_field :weight, placeholder: "weight" %>
      <%= form.text_field :height, placeholder: "height" %>
      <%= form.submit "投稿" %>
    <% end %>
  </div>
</div>

app/views/user_infos/index.html.erb
<%= image_tag "diet2.jpg", alt:"トップ画面",  class:"top-image"%> 
<h1>〜体重グラフ〜</h1>

<div class="contents row">
<% @user_infos.each do |user_info| %>
<div class="user_info"> 
<%= link_to '削除する', user_info_path(user_info.id), method: :delete %>
 <div class="weight">
      日付：<%= user_info.created_at.strftime("%m月%d日") %>
    </div>
    <div class="BMI">
      体重：<%= user_info.weight %>
    </div>
  </div>
<% end %>
</div>

<html lang="ja">

<head>
  <meta charset="utf-8">
　<title>グラフ</title> 
</head>
<body>
  <canvas id="myLineChart"></canvas>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>

  <script>
  var ctx = document.getElementById("myLineChart");
  var myLineChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: [<% @user_infos.each_with_index do |user_info| %> "<%= user_info.created_at.strftime("%m月%d日") %>" ,<% end %>],
      datasets: [
        
     
        {
          label: 'Weight',
          data: [ <% @user_infos.each_with_index do |user_info| %><%= user_info.weight %> ,<% end %> ],
          borderColor: "rgba(0,0,255,1)",
          backgroundColor: "rgba(0,0,0,0)"
        },  

      ],
    },
    options: {
      title: {
        display: true,
        
      },
      scales: {
        yAxes: [{
          ticks: {
            suggestedMax: 40,
            suggestedMin: 0,
            stepSize: 10,
            callback: function(value, index, values){
              return  value +  'kg'
            }
          }
        }]
      },
    }
  });
  </script>
</body>

</html>

app/views/user_infos/new.html.erb
<div class="items-sell-main">
    <h2 class="items-sell-title">体重情報を入力</h2>
    <%= form_with(model: @user_info, local: true) do |form| %>


<div class="new-items">
      <div class="weight-bold-text">
        身長
      </div>
      
       <%= form.text_field :height, class:"input-default", placeholder: "height" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          体重     
        </div>
         <%= form.text_field :weight,class:"input-default", placeholder: "weight" %>
      </div>
      <div class="sell-btn-contents">
      <%= form.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    </div>
    <% end %>

app/views/users/show.html.erb
<p>MyPage <%= @user_info.height %><<%= @user_info.weight %></p>